### ISSUE TITLE
rpc error: code = NotFound desc = rpc error: code =

### ISSUE THREAD

**Issue by vietnnit** [allora-network/allora-chain#143]
when I delegate I got the error
"rpc error: code = NotFound desc = rpc error: code = NotFound desc = account allo1zlzsvvan4fvfamcgn58qf9mg652j579l4exyrm not found: key not found"

could you show what is my probleam?

Thanks!

**Comment by xmariachi** [comment]
Hi @vietnnit , 
I believe this account needs funding. Could you please try adding it some funds?

**Comment by vietnnit** [comment]
> funding

I will try!
Thanks!
