### ISSUE TITLE
Git tags should not be overwritten

### ISSUE THREAD

**Issue by qezz** [allora-network/allora-chain#195]
Overwriting Git tags, also known as "re-tagging", is not the best idea.
This article has good explanation  - https://git-scm.com/docs/git-tag#_on_re_tagging

Please don't use tags like `latest`. If you need a moving label for master branch, this is what Git branches are for.

**Comment by relyt29** [comment]
@vladupshot

**Comment by qezz** [comment]
It's been some time since I complained on the issue. Fortunately, since then we (Chorus One) have published a book on Open Source Engineering, where this particular problem is described.

It's a good read, and I can recommend it to all blockchain engineers

https://handbook.chorus.one/node-software/release-engineering.html#no-retagging

**Comment by relyt29** [comment]
@okedeji @mgladson @kihahu 

can one of you take a look at this? I don't think we're still doing this?

I don't have context to see if we can close this ticket or not

**Comment by qezz** [comment]
I think it's still relevant

<img width="249" alt="image" src="https://github.com/user-attachments/assets/8f68a971-5208-4fa4-8f1f-a673a0ff4acf">

**Comment by relyt29** [comment]
I think we finally stopped doing this, we have new processes for releases if you'll look now, the last "latest" was three weeks ago

and on top of that I have now deleted it 

```bash
➜  allora-chain git:(dev) git push --delete origin latest
To github:allora-network/allora-chain
 - [deleted]           latest
```

Thanks for flagging this
