### ISSUE TITLE
panic: unknown field "inflation_max" in types.Params

### ISSUE THREAD

**Issue by ivanxue** [allora-network/allora-chain#351]
I am trying to running the full node, but got the following errors

> panic: unknown field "inflation_max" in types.Params

`goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x111a35108?, {0xc0010f4a00?, 0xc0000a5b08?, 0xc0023f5840?}, {0x10efeedb0?, 0xc0010a7960?})
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/codec/proto_codec.go:219 +0x3b
github.com/allora-network/allora-chain/x/mint/module.AppModule.InitGenesis({{{0x10f04b588, 0xc00090aa90}}, {{0x10f0254a0, 0xc00090aa90}, {0x10efd2f80, 0xc000ad63c0}, {0x15892d7f8, 0xc000e5d238}, {0x15892d870, 0xc00109fc00}, ...}, ...}, ...)
	/Users/queeniezhang/allora-chain/x/mint/module/module.go:124 +0x94
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x10f009c70, 0x110d11c40}, {0x10f025d60, 0xc00159c6c0}, {{0x0, 0x0}, {0xc0023f4957, 0x7}, 0x0, ...}, ...}, ...)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/types/module/module.go:505 +0x694
github.com/cosmos/cosmos-sdk/runtime.(*App).InitChainer(_, {{0x10f009c70, 0x110d11c40}, {0x10f025d60, 0xc00159c6c0}, {{0x0, 0x0}, {0xc0023f4957, 0x7}, 0x0, ...}, ...}, ...)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/runtime/app.go:188 +0xdf
github.com/allora-network/allora-chain/app.NewAlloraApp.func1({{0x10f009c70, 0x110d11c40}, {0x10f025d60, 0xc00159c6c0}, {{0x0, 0x0}, {0xc0023f4957, 0x7}, 0x0, {0x25f3dc06, ...}, ...}, ...}, ...)
	/Users/queeniezhang/allora-chain/app/app.go:269 +0x125
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0015a46c8, 0xc001248310)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/baseapp/abci.go:105 +0x6a2
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.InitChain(...)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/cmt_abci.go:32
github.com/cometbft/cometbft/abci/client.(*localClient).InitChain(0x0?, {0x10f00a3e0?, 0x110d11c40?}, 0x15893a818?)
	/Users/queeniezhang/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/abci/client/local_client.go:120 +0xcd
github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChain(0xc002275de8, {0x10f00a3e0, 0x110d11c40}, 0xc001248310)
	/Users/queeniezhang/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/proxy/app_conn.go:78 +0x170
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0x10d9b01fe, 0x6}}, {0xc0023f4957, 0x7}, 0x1, ...}, ...)
	/Users/queeniezhang/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/replay.go:336 +0xfb3
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc00108d3e0, {0x10f00a338, 0xc00226d9f0}, {0x10f029e28, 0xc000f99260})
	/Users/queeniezhang/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/consensus/replay.go:274 +0x425
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0x10d9b01fe, 0x6}}, {0xc0023f4957, 0x7}, ...}, ...)
	/Users/queeniezhang/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/node/setup.go:182 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x10f00a338, 0xc00226d9f0}, 0xc0000ee8c0, {0x10efeef60, 0xc0014a28c0}, 0xc0015f8460, {0x10efd3020, 0xc000e41530}, 0xc00108e248, 0x10efc0af0, ...)
	/Users/queeniezhang/go/pkg/mod/github.com/cometbft/cometbft@v0.38.6/node/node.go:350 +0x5b7
github.com/cosmos/cosmos-sdk/server.startCmtNode({0x10f00a338, 0xc00226d9f0}, 0xc0000ee8c0, {0x10f04b650, 0xc000613988}, 0xc0013f1600)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/start.go:368 +0x42f
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0x7ff7b4a6fa2d, 0x6}, 0x0, {0xc000f915b0, 0x7}, {0x10da0bad4, 0x1}, {0x10da0bad4, 0x1}, ...}, ...}, ...)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/start.go:314 +0x188
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x10f02d5f8, 0xc00147c420}, 0x0, {0x0, 0x0}, {0x10f04b588, ...}, ...}, ...)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/start.go:232 +0x2f3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/start.go:190 +0x5e
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc0013f1600, 0xc00108fa08)
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/start.go:566 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc0012fe008, {0xc001304c40?, 0x0?, 0x7?})
	/Users/queeniezhang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.5/server/start.go:189 +0x212
github.com/spf13/cobra.(*Command).execute(0xc0012fe008, {0xc001304bd0, 0x7, 0x7})
	/Users/queeniezhang/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0011bc308)
	/Users/queeniezhang/go/pkg/mod/github.com/spf13/cobra@v1.8.0/comma`

**Comment by relyt29** [comment]
not sure what this issue is, but likely has gone away since the codebase has changed a lot since june 13
