### ISSUE TITLE
I can't faucet from https://faucet.testnet.allora.network/

### ISSUE THREAD

**Issue by vietnnit** [allora-network/allora-chain#359]
I got the message "Sorry, you've exceeded the daily limit for requests from this address or IP" with my addr allo1duluurxezqqsrr02f8008n5pvx4r8k2fvu99v0
Help me please!

**Comment by vietnnit** [comment]
Now I can doing faucet but my balance is zero. Could you help me!
allorad query bank balances allo1duluurxezqqsrr02f8008n5pvx4r8k2fvu99v0

**Comment by relyt29** [comment]
please see discord server for end user support, this is not the appropriate venue for these kinds of issues
