### ISSUE TITLE
Error exec /scripts/l1_node.sh: no such file or directory when run full node.

### ISSUE THREAD

**Issue by khanhtq** [allora-network/allora-chain#383]
Hi, 
Thank for you help
I got error "exec /scripts/l1_node.sh: no such file or directory" after run docker compose up -d when run full node by this guideline.
Could you please help check and fix it if need?
Thanks!

**Comment by thuthuyng0119** [comment]
This issue resolved by use this command:
git clone https://github.com/allora-network/allora-chain.git --config core.autocrlf=false
Thanks!
