### ISSUE TITLE
could not get chain params error

### ISSUE THREAD

**Issue by KhalidMehmood05** [allora-network/allora-chain#429]
ERR could not get chain params error="proto: wrong wireType = 0 for field MaxActiveForecastersQuantile"

I’m getting this error from last day, I tried many times but same error occurs every time, how to solve it?

**Comment by kpeluso** [comment]
Please try again using latest versions of `allora-chain` and `allora-inference-base`

**Comment by KhalidMehmood05** [comment]
I’m using updated version already but it’s showing error every time

**Comment by relyt29** [comment]
please see discord server for end user support, this is not the appropriate venue for these kinds of issues
